### ISSUE TITLE
Configuration Confusion 

### ISSUE THREAD

**Issue by CMaxim77** [bradcrc/Now-Playing-Card#2]
I love this idea! But there isn’t a full example of how to use this in the floorplan? 

Actually, I’m trying to use this in a different way. I believe it should work. 
I took a picture of my Entertainment Stand that has a electric fireplace insert. Grabbed a gif image from google of moving fire. My thought was to make a tap_toggle so when the state is on the gif shows up in my fireplace.

I was able to get all the styles but from there I’m confused.

Is there any config examples anywhere other then the readme section?

Thanks!

**Comment by bradcrc** [comment]
I don't think that should work.
 
from the readme:  **The card only shows the entity_picture while the status is playing**

but a regular conditional image card might work if you just add the same CSS style.
 
if nothing else,  the javascript is pretty simple,  just change the part about playing in your copy or comment it out.   a little googling should get you there.
 
finally since it's a fixed image and not dynamic,  it'd be a valid  (and probably better) solution to just edit the source fire gif to be the correct perspective and then not even worry about CSS transitions.


good luck!

**Comment by CMaxim77** [comment]
Thanks for the reply! I’ll have a good look around! I appreciate you!
