### ISSUE TITLE
0.110 Lovelace Cannot read property ‘states’ of undefined

### ISSUE THREAD

**Issue by LukaszP2** [bradcrc/Now-Playing-Card#4]
After upgrade HA to 0.110 I get Cannot read property ‘states’ of undefined. After disable now playing card everything works ok. Can you help me?

**Comment by bradcrc** [comment]
bummer.  looks like 110 broke both these custom cards.
 
that sucks.  I'll update the docs to let everyone know.   

thanks for letting me know.

**Comment by DKFrederik** [comment]
I can comfirm this. This is actually kind of sad I was using this card quite alot

**Comment by bradcrc** [comment]
Spent a few hours looking into this today.   It appears that the card works fine on its own in lovelace.   It only generates this error when it's used inside of a picture elements card.
 
It appears the hass.states is not being passed from the picture elements container.    I'm guessing this is a defect in the picture elements card, since the custom now playing card works outside of picture elements,  and [the documentation on custom cards ](https://developers.home-assistant.io/docs/frontend/custom-ui/lovelace-custom-card/) shows the exact code which is used by this custom card.
 
It does not appear at this time that there is anything that can be done from this card,  hopefully they will either fix the issue with the picture elements card, or update the documentation to show a different way to pull the states from an entity when referenced from inside picture elements.

**Comment by rigrig** [comment]
I ran into this issue in HA 0.110.0, but after upgrading to 0.110.2 I tried again and it seems fixed now.
